#include "irqs.h"

void NMI_Handler(void){ while(1) {;}}
void HardFault_Handler(void){ while(1) {;}}
void MemManage_Handler(void){ while(1) {;}}
void BusFault_Handler(void){ while(1) {;}}
void UsageFault_Handler(void){ while(1) {;}}
void SVC_Handler(void){ while(1) {;}}
void DebugMon_Handler(void){ while(1) {;}}
void PendSV_Handler(void){ while(1) {;}}
void SysTick_Handler(void){ while(1) {;}}

void SUPC_IrqHandler(void){ while(1) {;}}
void RSTC_IrqHandler(void){ while(1) {;}}
void RTC_IrqHandler(void){ while(1) {;}}
void RTT_IrqHandler(void){ while(1) {;}}
void WDT_IrqHandler(void){ while(1) {;}}
void PMC_IrqHandler(void){ while(1) {;}}
void EFC0_IrqHandler(void){ while(1) {;}}
void EFC1_IrqHandler(void){ while(1) {;}}
void DBGU_IrqHandler(void){ while(1) {;}}
void HSMC4_IrqHandler(void){ while(1) {;}}
void PIOA_IrqHandler(void){ while(1) {;}}
void PIOB_IrqHandler(void){ while(1) {;}}
void PIOC_IrqHandler(void){ while(1) {;}}
void USART0_IrqHandler(void){ while(1) {;}}
void USART1_IrqHandler(void){ while(1) {;}}
void USART2_IrqHandler(void){ while(1) {;}}
void USART3_IrqHandler(void){ while(1) {;}}
void MCI0_IrqHandler(void){ while(1) {;}}
void TWI0_IrqHandler(void){ while(1) {;}}
void TWI1_IrqHandler(void){ while(1) {;}}
void SPI0_IrqHandler(void){ while(1) {;}}
void SSC0_IrqHandler(void){ while(1) {;}}
void TC0_IrqHandler(void){ while(1) {;}}
void TC1_IrqHandler(void){ while(1) {;}}
void TC2_IrqHandler(void){ while(1) {;}}
void PWM_IrqHandler(void){ while(1) {;}}
void ADCC0_IrqHandler(void){ while(1) {;}}
void ADCC1_IrqHandler(void){ while(1) {;}}
void HDMA_IrqHandler(void){ while(1) {;}}
void USBD_IrqHandler(void){ while(1) {;}}
void IrqHandlerNotUsed(void){ while(1) {;}}
